name: Docker Env Image CI

on:
  push:
    branches:
      - master # 触发分支
env:
  REPO: naturelr/blog-env

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
    
      - name: Display Tag or Commit ID
        run: | 
              if [ "${{ github.event_name }}" == "push" ]; then
                if [ "${{ startsWith(github.ref, 'refs/tags/') }}" == "true" ]; then
                  echo "Tag: ${{ github.ref }}"
                  echo "TAG_NAME=${{ github.ref }}" >> $GITHUB_ENV
                else
                  short_commit_id=$(git rev-parse --short "${{ github.sha }}")
                  echo "Short Commit ID: $short_commit_id"
                  echo "TAG_NAME=$short_commit_id" >> $GITHUB_ENV
                fi
              fi

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
  
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.REPO }}:${{ env.TAG_NAME }},${{ env.REPO }}:latest
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          target: "build"

      - name: Update repo description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ env.REPO }}
